### ISSUE TITLE
The config file for `train_CLAP_DomainNet_ViTB.yaml`

### ISSUE THREAD

**Issue by SydCS** [YichaoCai1/CLAP#1]
Hello. Nice work!
I wonder if it might be possible to have access to the config file for `train_CLAP_DomainNet_ViTB.yaml`?
Thank you in advance for your help.

**Comment by SydCS** [comment]
Also, I want to check if my understanding is right.
In the results of DomainNet in Table 3, are they calculated after tuning the disentangled network on the prompts of DomainNet, or on the prompts of any dataset like VLCS?
Thanks a million.

**Comment by YichaoCai1** [comment]
Hi @SydCS ,

Thank you for your message.

For the training configuration, all the configurations are archived in the artifacts directory (`runs/`) within this repository, e.g., you can find the configuration for training based on the ViT-B model on DomainNet at:
`runs/Results_CLAP_ViTB/DomainNet/config.yml`.

The networks are tuned based on prompts specific to each dataset, as the class names differ across datasets. However, the template-style words used to generate these prompts are shared across datasets. These templates can be found in:
`data/prompts_template`.

Thank you again!
